### PR TITLE
Ported to Godot 3 Alpha 2

### PR DESCRIPTION
**Pull request by timschellenberg**
Ported aseprite-import to Godot 3's new Import Dock system as a .json file importer.

New settings:
* Sheet Image: If the .json and the .png file do not have matching filenames and are in the same directory, you can specify an absolute path to the image file here. The filename given in the .json file is ignored in favor of this system, because it is not visually apparent without opening the .json file in a text editor to check.
* Post Script: An optional `.gd` script that has its `post_import( scene_root )` method called after the importing process is finished. It is expected to return the changed scene's root node.
* Autoplay Animation: Since resources are no longer easily editable after import, it's not possible to easily change the animation you want to autoplay at scene load through the Editor any more. This alleviates that specific issue, which I figured would be more common than most other edits.

As mention in the *Autoplay Animation* description, one drawback of the new import system is that the output scene file is not directly editable by opening the .json file in the Godot editor any more, meaning all the preservation mechanics are useless now.
I've left the code for all of it intact and only commented out the snippet that loads the scene left from the last import, in case you can figure out a way to re-implement this in the future.

Also, sorry for renaming two EditorPlugin files. This is the way I organize all my plug-ins and I got really confused trying to use the original filenames. Feel free to revert these after merging.
The `EditorImportPlugin` was rewritten almost entirely anyway, while the vast majority of changes are inside the `sheet2scene.gd` file, which kept its name.

### CODE REVIEW

**Comment by leonkrause** [comment]
Wow, nice work. I'll take a better look at this when 3.0-beta is out

**Comment by tiniuclx** [comment]
[The beta is out!](https://godotengine.org/article/dev-snapshot-godot-3-0-beta-1) I would love to see this working in Godot 3, it's very useful and integrates seamlessly in my workflow.

**Comment by timschellenberg** [comment]
If you aren't aware @tiniuclx, you can just download my branch from here:
[https://github.com/leoddd/aseprite-import/archive/godot-3.zip](https://github.com/leoddd/aseprite-import/archive/godot-3.zip)

It works as-is in Beta 1.

**Comment by leonkrause** [comment]
I see you moved the `README.markdown` and `LICENSE` files outside the addon directory into the root directory. I understand this allows Github to read and display them in some places.
But this also causes those files to be extracted into users' project directories if there aren't files by that name yet, which is confusing. So please keep them where they are.

**Comment by leonkrause** [comment]
Also, I haven't made any releases since version 0.1, so if you update the version to 2.0 (or even 1.0 if you prefer) that's enough, no need for 3.1

**Comment by timschellenberg** [comment]
Moved the README and the LICENSE file back (I actually had a duplicate of the LICENSE by accident) and changed the version 1.0.
The version was actually at 3.1 because I was upping it by 1 every time I compared two versions locally, just so I can tell the difference. I forgot to reset it when I was done.

**Comment by leonkrause** [comment]
Good work, thank you.

**Comment by timschellenberg** [comment]
No problem!

**Pull request merged**
